<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- 多目标框架 -->
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Authors>HandsomeChen0407</Authors>
    <Company>Cjora.MQ</Company>
    <Copyright>Copyright © 2025 HandsomeChen0407</Copyright>
    <Description>Cjora.MQ 是一个高性能、可扩展的 .NET 消息队列基础设施库，统一封装 Kafka / MQTT，提供标准化的 Consumer / Producer / Runtime 生命周期管理。</Description>
    <Name />
    <PackageIconUrl />
    <PackageId>Cjora.MQ</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageLicenseUrl />
    <PackageProjectUrl>https://github.com/HandsomeChen0407/Cjora.MQ</PackageProjectUrl>
    <PackageReleaseNotes>1、新增  MQTT 协议版本 ProtocolVersion：可选值：V310，V311, V500
2、新增 TraceId 属性名称（用于从 MQTT 发布结果的 UserProperties 中提取 TraceId），例如：腾讯云 MQTT 使用 "$__messageId" 作为消息ID</PackageReleaseNotes>
    <PackageTags />
    <Product>Cjora.MQ</Product>
    <RepositoryType />
    <RepositoryUrl />
    <Version>2.4.0</Version>
    <PackageIcon />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
    <PackageReference Include="MQTTnet" Version="5.0.1.1416" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
